// 100+ common Italian A1-A2 vocabulary words
// Each word: { id, italian, english, example, emoji }

export const VOCABULARY = [
  // Greetings & basics
  { id: 1, italian: "ciao", english: "hello / bye", example: "Ciao, come stai?", emoji: "👋" },
  { id: 2, italian: "salve", english: "hello (formal)", example: "Salve, buongiorno!", emoji: "🤝" },
  { id: 3, italian: "arrivederci", english: "goodbye", example: "Arrivederci, a domani!", emoji: "👋" },
  { id: 4, italian: "buongiorno", english: "good morning", example: "Buongiorno, professore!", emoji: "🌅" },
  { id: 5, italian: "buonasera", english: "good evening", example: "Buonasera, signora Rossi.", emoji: "🌆" },
  { id: 6, italian: "buonanotte", english: "good night", example: "Buonanotte, dormi bene.", emoji: "🌙" },
  { id: 7, italian: "grazie", english: "thank you", example: "Grazie per l'aiuto!", emoji: "🙏" },
  { id: 8, italian: "prego", english: "you're welcome", example: "Prego, non c'è problema.", emoji: "😊" },
  { id: 9, italian: "scusa", english: "excuse me / sorry", example: "Scusa, dov'è la stazione?", emoji: "🙇" },
  { id: 10, italian: "per favore", english: "please", example: "Un caffè, per favore.", emoji: "🥺" },
  { id: 11, italian: "sì", english: "yes", example: "Sì, capisco.", emoji: "✅" },
  { id: 12, italian: "no", english: "no", example: "No, non lo so.", emoji: "❌" },
  { id: 13, italian: "bene", english: "well / good", example: "Sto bene, grazie!", emoji: "😄" },
  { id: 14, italian: "male", english: "badly / bad", example: "Mi sento male oggi.", emoji: "😞" },

  // People & family
  { id: 15, italian: "uomo", english: "man", example: "Quell'uomo è mio padre.", emoji: "👨" },
  { id: 16, italian: "donna", english: "woman", example: "La donna legge un libro.", emoji: "👩" },
  { id: 17, italian: "bambino", english: "child (m)", example: "Il bambino gioca nel parco.", emoji: "🧒" },
  { id: 18, italian: "ragazzo", english: "boy / boyfriend", example: "Il ragazzo è alto.", emoji: "👦" },
  { id: 19, italian: "ragazza", english: "girl / girlfriend", example: "La ragazza studia italiano.", emoji: "👧" },
  { id: 20, italian: "famiglia", english: "family", example: "La mia famiglia è grande.", emoji: "👨‍👩‍👧‍👦" },
  { id: 21, italian: "madre", english: "mother", example: "Mia madre cucina bene.", emoji: "👩‍👦" },
  { id: 22, italian: "padre", english: "father", example: "Mio padre lavora in ufficio.", emoji: "👨‍👧" },
  { id: 23, italian: "figlio", english: "son", example: "Hai un figlio?", emoji: "🧒" },
  { id: 24, italian: "figlia", english: "daughter", example: "Mia figlia ha cinque anni.", emoji: "👧" },
  { id: 25, italian: "fratello", english: "brother", example: "Mio fratello è più grande.", emoji: "👦" },
  { id: 26, italian: "sorella", english: "sister", example: "Mia sorella vive a Roma.", emoji: "👧" },
  { id: 27, italian: "amico", english: "friend (m)", example: "Il mio amico si chiama Marco.", emoji: "🧑" },
  { id: 28, italian: "nonno", english: "grandfather", example: "Mio nonno ha 80 anni.", emoji: "👴" },
  { id: 29, italian: "nonna", english: "grandmother", example: "Mia nonna fa la pasta.", emoji: "👵" },

  // Food & drink
  { id: 30, italian: "pane", english: "bread", example: "Compro il pane dal panettiere.", emoji: "🍞" },
  { id: 31, italian: "acqua", english: "water", example: "Bevo molta acqua.", emoji: "💧" },
  { id: 32, italian: "vino", english: "wine", example: "Un bicchiere di vino rosso.", emoji: "🍷" },
  { id: 33, italian: "caffè", english: "coffee", example: "Prendo un caffè al bar.", emoji: "☕" },
  { id: 34, italian: "latte", english: "milk", example: "Vuoi latte nello zucchero?", emoji: "🥛" },
  { id: 35, italian: "formaggio", english: "cheese", example: "Mi piace il formaggio italiano.", emoji: "🧀" },
  { id: 36, italian: "carne", english: "meat", example: "Non mangio la carne.", emoji: "🥩" },
  { id: 37, italian: "pesce", english: "fish", example: "Stasera mangiamo pesce.", emoji: "🐟" },
  { id: 38, italian: "frutta", english: "fruit", example: "La frutta è buona per la salute.", emoji: "🍎" },
  { id: 39, italian: "verdura", english: "vegetables", example: "Mangio tanta verdura.", emoji: "🥬" },
  { id: 40, italian: "mela", english: "apple", example: "Questa mela è rossa.", emoji: "🍎" },
  { id: 41, italian: "pomodoro", english: "tomato", example: "Aggiungo il pomodoro alla pasta.", emoji: "🍅" },
  { id: 42, italian: "pizza", english: "pizza", example: "La pizza margherita è famosa.", emoji: "🍕" },
  { id: 43, italian: "pasta", english: "pasta", example: "La pasta è pronta!", emoji: "🍝" },
  { id: 44, italian: "riso", english: "rice", example: "Mangio riso con verdure.", emoji: "🍚" },
  { id: 45, italian: "uovo", english: "egg", example: "Vorrei un uovo fritto.", emoji: "🥚" },
  { id: 46, italian: "zucchero", english: "sugar", example: "Un po' di zucchero nel caffè?", emoji: "🧁" },
  { id: 47, italian: "sale", english: "salt", example: "Il sale è sulla tavola.", emoji: "🧂" },

  // House & objects
  { id: 48, italian: "casa", english: "house / home", example: "La mia casa è vicino al mare.", emoji: "🏠" },
  { id: 49, italian: "porta", english: "door", example: "Chiudi la porta, per favore.", emoji: "🚪" },
  { id: 50, italian: "finestra", english: "window", example: "La finestra è aperta.", emoji: "🪟" },
  { id: 51, italian: "cucina", english: "kitchen", example: "La cucina è piccola ma bella.", emoji: "🍳" },
  { id: 52, italian: "camera", english: "room / bedroom", example: "La mia camera è al piano di sopra.", emoji: "🛏️" },
  { id: 53, italian: "letto", english: "bed", example: "Il letto è molto comodo.", emoji: "🛏️" },
  { id: 54, italian: "tavolo", english: "table", example: "Il libro è sul tavolo.", emoji: "🪑" },
  { id: 55, italian: "sedia", english: "chair", example: "Siediti su questa sedia.", emoji: "🪑" },
  { id: 56, italian: "chiave", english: "key", example: "Hai le chiavi di casa?", emoji: "🔑" },
  { id: 57, italian: "libro", english: "book", example: "Questo libro è interessante.", emoji: "📖" },
  { id: 58, italian: "penna", english: "pen", example: "Mi passi la penna?", emoji: "🖊️" },
  { id: 59, italian: "telefono", english: "phone", example: "Il telefono sta suonando.", emoji: "📱" },
  { id: 60, italian: "orologio", english: "watch / clock", example: "L'orologio è nuovo.", emoji: "⌚" },
  { id: 61, italian: "borsa", english: "bag", example: "La borsa è sulla sedia.", emoji: "👜" },
  { id: 62, italian: "occhiali", english: "glasses", example: "Non trovo i miei occhiali.", emoji: "👓" },

  // Common verbs
  { id: 63, italian: "essere", english: "to be", example: "Io sono italiano.", emoji: "✨" },
  { id: 64, italian: "avere", english: "to have", example: "Ho una macchina nuova.", emoji: "🤲" },
  { id: 65, italian: "fare", english: "to do / make", example: "Cosa fai stasera?", emoji: "🔨" },
  { id: 66, italian: "andare", english: "to go", example: "Vado a scuola.", emoji: "🚶" },
  { id: 67, italian: "mangiare", english: "to eat", example: "Mangiamo una pizza.", emoji: "🍽️" },
  { id: 68, italian: "bere", english: "to drink", example: "Bevo un bicchiere d'acqua.", emoji: "🥤" },
  { id: 69, italian: "dormire", english: "to sleep", example: "Dormo otto ore ogni notte.", emoji: "😴" },
  { id: 70, italian: "parlare", english: "to speak", example: "Parlo italiano un po'.", emoji: "💬" },
  { id: 71, italian: "capire", english: "to understand", example: "Capisco l'italiano.", emoji: "💡" },
  { id: 72, italian: "vedere", english: "to see", example: "Vedo un film.", emoji: "👀" },
  { id: 73, italian: "sentire", english: "to hear / feel", example: "Sento la musica.", emoji: "👂" },
  { id: 74, italian: "vivere", english: "to live", example: "Vivo a Milano.", emoji: "🏡" },
  { id: 75, italian: "studiare", english: "to study", example: "Studio l'italiano ogni giorno.", emoji: "📚" },
  { id: 76, italian: "lavorare", english: "to work", example: "Lavoro in un ufficio.", emoji: "💼" },
  { id: 77, italian: "comprare", english: "to buy", example: "Compro il pane al supermercato.", emoji: "🛒" },
  { id: 78, italian: "volere", english: "to want", example: "Voglio un gelato.", emoji: "🤩" },
  { id: 79, italian: "potere", english: "to be able to", example: "Posso entrare?", emoji: "💪" },
  { id: 80, italian: "dovere", english: "must / to have to", example: "Devo studiare.", emoji: "📌" },
  { id: 81, italian: "sapere", english: "to know", example: "So la risposta.", emoji: "🧠" },

  // Adjectives
  { id: 82, italian: "grande", english: "big / great", example: "È una città grande.", emoji: "🐘" },
  { id: 83, italian: "piccolo", english: "small", example: "Ho un gatto piccolo.", emoji: "🐭" },
  { id: 84, italian: "bello", english: "beautiful", example: "Che bello!", emoji: "😍" },
  { id: 85, italian: "brutto", english: "ugly", example: "Il tempo è brutto oggi.", emoji: "😬" },
  { id: 86, italian: "buono", english: "good", example: "Questo cibo è buono.", emoji: "😋" },
  { id: 87, italian: "nuovo", english: "new", example: "Ho una macchina nuova.", emoji: "🆕" },
  { id: 88, italian: "vecchio", english: "old", example: "Mio nonno è vecchio ma attivo.", emoji: "👴" },
  { id: 89, italian: "caldo", english: "hot", example: "Oggi fa caldo!", emoji: "🔥" },
  { id: 90, italian: "freddo", english: "cold", example: "D'inverno fa freddo.", emoji: "❄️" },
  { id: 91, italian: "felice", english: "happy", example: "Sono molto felice!", emoji: "😄" },
  { id: 92, italian: "triste", english: "sad", example: "Il film mi rende triste.", emoji: "😢" },
  { id: 93, italian: "stanco", english: "tired", example: "Sono stanco dopo il lavoro.", emoji: "😩" },
  { id: 94, italian: "facile", english: "easy", example: "L'italiano è facile?", emoji: "✨" },
  { id: 95, italian: "difficile", english: "difficult", example: "Questo esercizio è difficile.", emoji: "🤔" },
  { id: 96, italian: "importante", english: "important", example: "È importante studiare.", emoji: "⭐" },

  // Places
  { id: 97, italian: "città", english: "city", example: "Roma è una città bellissima.", emoji: "🏙️" },
  { id: 98, italian: "scuola", english: "school", example: "Vado a scuola alle otto.", emoji: "🏫" },
  { id: 99, italian: "ristorante", english: "restaurant", example: "Mangiamo al ristorante.", emoji: "🍽️" },
  { id: 100, italian: "albergo", english: "hotel", example: "L'albergo è in centro.", emoji: "🏨" },
  { id: 101, italian: "stazione", english: "station", example: "La stazione è vicina.", emoji: "🚉" },
  { id: 102, italian: "strada", english: "street / road", example: "La strada è lunga.", emoji: "🛣️" },
  { id: 103, italian: "piazza", english: "square (plaza)", example: "La piazza è piena di gente.", emoji: "⛲" },
  { id: 104, italian: "ufficio", english: "office", example: "Lavoro in ufficio.", emoji: "🏢" },
  { id: 105, italian: "banca", english: "bank", example: "La banca apre alle 9.", emoji: "🏦" },
  { id: 106, italian: "farmacia", english: "pharmacy", example: "Cerco una farmacia.", emoji: "💊" },

  // Time
  { id: 107, italian: "giorno", english: "day", example: "Che giorno è oggi?", emoji: "☀️" },
  { id: 108, italian: "notte", english: "night", example: "Buonanotte, a domani!", emoji: "🌃" },
  { id: 109, italian: "mattina", english: "morning", example: "La mattina bevo il caffè.", emoji: "🌄" },
  { id: 110, italian: "sera", english: "evening", example: "La sera guardo la TV.", emoji: "🌆" },
  { id: 111, italian: "oggi", english: "today", example: "Oggi fa bel tempo.", emoji: "📅" },
  { id: 112, italian: "domani", english: "tomorrow", example: "Domani vado al cinema.", emoji: "⏭️" },
  { id: 113, italian: "ieri", english: "yesterday", example: "Ieri ho lavorato molto.", emoji: "⏮️" },
  { id: 114, italian: "settimana", english: "week", example: "Lavoro cinque giorni a settimana.", emoji: "📆" },
  { id: 115, italian: "mese", english: "month", example: "Il mese ha 30 giorni.", emoji: "🗓️" },
  { id: 116, italian: "anno", english: "year", example: "Quest'anno vado in Italia.", emoji: "🎉" },
  { id: 117, italian: "ora", english: "hour / now", example: "Che ora è?", emoji: "🕐" },
  { id: 118, italian: "tempo", english: "time / weather", example: "Il tempo vola!", emoji: "⏰" },

  // Nature
  { id: 119, italian: "sole", english: "sun", example: "Il sole splende oggi.", emoji: "☀️" },
  { id: 120, italian: "luna", english: "moon", example: "La luna è piena stasera.", emoji: "🌕" },
  { id: 121, italian: "cielo", english: "sky", example: "Il cielo è azzurro.", emoji: "☁️" },
  { id: 122, italian: "mare", english: "sea", example: "Andiamo al mare!", emoji: "🌊" },
  { id: 123, italian: "montagna", english: "mountain", example: "La montagna è alta.", emoji: "⛰️" },
  { id: 124, italian: "albero", english: "tree", example: "L'albero è molto vecchio.", emoji: "🌳" },
  { id: 125, italian: "fiore", english: "flower", example: "Che bel fiore!", emoji: "🌸" },
  { id: 126, italian: "neve", english: "snow", example: "La neve è bianca.", emoji: "❄️" },
  { id: 127, italian: "pioggia", english: "rain", example: "La pioggia cade forte.", emoji: "🌧️" },

  // Animals
  { id: 128, italian: "cane", english: "dog", example: "Il mio cane è fedele.", emoji: "🐶" },
  { id: 129, italian: "gatto", english: "cat", example: "Il gatto dorme sul divano.", emoji: "🐱" },
  { id: 130, italian: "cavallo", english: "horse", example: "Il cavallo corre veloce.", emoji: "🐴" },
  { id: 131, italian: "uccello", english: "bird", example: "L'uccello canta al mattino.", emoji: "🐦" },

  // Misc common
  { id: 132, italian: "tempo", english: "weather", example: "Il tempo è bello.", emoji: "🌤️" },
  { id: 133, italian: "amore", english: "love", example: "L'amore è importante.", emoji: "❤️" },
  { id: 134, italian: "lavoro", english: "work / job", example: "Il mio lavoro è interessante.", emoji: "💼" },
  { id: 135, italian: "macchina", english: "car", example: "La macchina è rossa.", emoji: "🚗" },
  { id: 136, italian: "treno", english: "train", example: "Il treno arriva alle 10.", emoji: "🚆" },
  { id: 137, italian: "aereo", english: "airplane", example: "L'aereo parte alle 8.", emoji: "✈️" },
  { id: 138, italian: "soldi", english: "money", example: "Non ho molti soldi.", emoji: "💰" },
  { id: 139, italian: "nome", english: "name", example: "Come ti chiami di nome?", emoji: "🏷️" },
  { id: 140, italian: "scusa", english: "sorry", example: "Scusa per il ritardo!", emoji: "😅" },
];

export function getWordById(id) {
  return VOCABULARY.find((w) => w.id === id);
}